// AUTO-GENERATED by scripts/build-content-registry.ts — do not edit by hand.
// Re-run `npm run build:content-registry` whenever content/ changes.

import type { ReviewedArticleRef } from './contentBridge';

export const GENERATED_ARTICLES: ReadonlyArray<ReviewedArticleRef> = [
  { slug: "ashoka", category: 'herbs', title: "Ashoka · The Tree That Removes Sorrow", phases: ['menstrual', 'luteal'] as any, published: false },
  { slug: "lodhra", category: 'herbs', title: "Lodhra · The Astringent Bark for the Uterus", phases: ['menstrual', 'luteal'] as any, published: false },
  { slug: "shatavari", category: 'herbs', title: "Shatavari · The Queen of Women's Herbs", phases: ['menstrual', 'follicular', 'ovulation', 'luteal'] as any, published: false },
  { slug: "triphala", category: 'herbs', title: "Triphala · The Three Fruits", phases: ['menstrual', 'follicular', 'ovulation', 'luteal'] as any, published: false },
  { slug: "turmeric-haridra", category: 'herbs', title: "Turmeric · Haridra · The Golden Anti-Inflammatory", phases: ['menstrual', 'luteal'] as any, published: false },
  { slug: "basal-body-temperature", category: 'hormone-science', title: "Basal Body Temperature · Reading the Body's Thermostat", phases: ['menstrual', 'follicular', 'ovulation', 'luteal'] as any, published: false },
  { slug: "estrogen-the-rise", category: 'hormone-science', title: "Estrogen · The Hormone That Builds", phases: ['follicular', 'ovulation'] as any, published: false },
  { slug: "lh-surge", category: 'hormone-science', title: "The LH Surge · Your Body's Ovulation Trigger", phases: ['ovulation'] as any, published: false },
  { slug: "progesterone-the-hold", category: 'hormone-science', title: "Progesterone · The Hormone That Holds", phases: ['luteal'] as any, published: false },
  { slug: "follicular-inner-spring", category: 'phase-wisdom', title: "Follicular · The Inner Spring", phases: ['follicular'] as any, published: false },
  { slug: "luteal-inner-autumn", category: 'phase-wisdom', title: "Luteal · The Inner Autumn", phases: ['luteal'] as any, published: false },
  { slug: "menstrual-inner-winter", category: 'phase-wisdom', title: "Menstrual · The Inner Winter", phases: ['menstrual'] as any, published: false },
  { slug: "ovulation-inner-summer", category: 'phase-wisdom', title: "Ovulation · The Inner Summer", phases: ['ovulation'] as any, published: false },
  { slug: "follicular-warm-sesame-abhyanga", category: 'rituals', title: "Warm Sesame Abhyanga · The Rebuilding Week Self-Massage", phases: ['follicular'] as any, published: false },
  { slug: "luteal-slow-kitchari", category: 'rituals', title: "Slow-Cooked Kitchari · The Perfect Late-Luteal Meal", phases: ['luteal'] as any, published: false },
  { slug: "menstrual-warm-castor-oil-belly-pack", category: 'rituals', title: "Warm Castor Oil Belly Pack · For Cramps and Heaviness", phases: ['menstrual'] as any, published: false },
  { slug: "ovulation-nadi-shodhana", category: 'rituals', title: "Nadi Shodhana · Keeping Pitta's Fire Steady, Not Scorching", phases: ['ovulation'] as any, published: false },
  { slug: "welcome-first-ritual", category: 'rituals', title: "Your First Ritual · A Breathing-In", phases: ['menstrual', 'follicular', 'ovulation', 'luteal'] as any, published: false },
  { slug: "modern-rajasvala", category: 'ritumaticharya', title: "Rajasvala Charya for a Working Woman", phases: ['menstrual'] as any, published: false },
  { slug: "period-myths-debunked", category: 'ritumaticharya', title: "Period Myths · What's Ayurveda, What's Culture, What's Neither", phases: ['menstrual'] as any, published: false },
  { slug: "rajasvala-charya", category: 'ritumaticharya', title: "Rajasvala-charya · The Classical Menstrual Regimen", phases: ['menstrual'] as any, published: false },
];
