#!/usr/bin/env node
/**
 * Reads content/**\/*.md, parses YAML frontmatter, and writes
 * src/companion/culture/articleRegistry.generated.ts so the
 * companion can list and gate citations on published articles
 * without drifting from disk.
 *
 * Run via `npm run build:content-registry`. The generated file is
 * checked in so app builds don't depend on running this script.
 */

import * as fs from 'fs';
import * as path from 'path';
import matter from 'gray-matter';

interface ArticleFrontmatter {
  slug?: string;
  title?: string;
  category?: string;
  phases?: string[];
  tier?: string;
  published?: boolean;
}

const ROOT = path.resolve(__dirname, '..');
const CONTENT_DIR = path.join(ROOT, 'content');
const OUT_FILE = path.join(
  ROOT,
  'src',
  'companion',
  'culture',
  'articleRegistry.generated.ts'
);

const ALLOWED_CATEGORIES = [
  'phase-wisdom',
  'rituals',
  'herbs',
  'hormone-science',
  'ritumaticharya',
] as const;
type Category = (typeof ALLOWED_CATEGORIES)[number];

interface Entry {
  slug: string;
  category: Category;
  title: string;
  phases: string[];
  published: boolean;
  sourcePath: string;
}

function walkMarkdown(dir: string, acc: string[] = []): string[] {
  if (!fs.existsSync(dir)) return acc;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walkMarkdown(p, acc);
    else if (e.isFile() && e.name.endsWith('.md')) acc.push(p);
  }
  return acc;
}

function categoryFromPath(p: string): Category | null {
  const rel = path.relative(CONTENT_DIR, p);
  const first = rel.split(path.sep)[0];
  return (ALLOWED_CATEGORIES as readonly string[]).includes(first)
    ? (first as Category)
    : null;
}

function main() {
  const files = walkMarkdown(CONTENT_DIR);
  const entries: Entry[] = [];

  for (const file of files) {
    const raw = fs.readFileSync(file, 'utf8');
    const { data } = matter(raw) as { data: ArticleFrontmatter };
    const category = categoryFromPath(file);
    if (!category) {
      console.warn(`skip (unknown category): ${file}`);
      continue;
    }
    const slug =
      data.slug ??
      path
        .basename(file, '.md')
        .replace(/^\d+[-_]/, '')
        .toLowerCase();
    const title = data.title ?? slug;
    const phases = Array.isArray(data.phases)
      ? data.phases.filter((p): p is string => typeof p === 'string')
      : [];
    entries.push({
      slug,
      category,
      title,
      phases,
      published: data.published === true,
      sourcePath: path.relative(ROOT, file),
    });
  }

  entries.sort((a, b) => `${a.category}/${a.slug}`.localeCompare(`${b.category}/${b.slug}`));

  const header = `// AUTO-GENERATED by scripts/build-content-registry.ts — do not edit by hand.
// Re-run \`npm run build:content-registry\` whenever content/ changes.

import type { ReviewedArticleRef } from './contentBridge';

export const GENERATED_ARTICLES: ReadonlyArray<ReviewedArticleRef> = [
`;

  const body = entries
    .map((e) => {
      const phasesStr =
        e.phases.length > 0
          ? `[${e.phases.map((p) => `'${p}'`).join(', ')}]`
          : 'undefined';
      return `  { slug: ${JSON.stringify(e.slug)}, category: '${e.category}', title: ${JSON.stringify(
        e.title
      )}, phases: ${phasesStr} as any, published: ${e.published} },`;
    })
    .join('\n');

  const footer = `\n];\n`;

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, header + body + footer, 'utf8');
  console.log(
    `wrote ${entries.length} articles (${entries.filter((e) => e.published).length} published) -> ${path.relative(ROOT, OUT_FILE)}`
  );
}

main();
